before_script:
  - "cd ./csharp/library/"

stages:
  - native
  - dotnet
  - cleanup

Build Autowrap CSharp Linux x64 Native:
  stage: native
  tags:
    - linux
    - dmd
    - dub 
  only:
    - csharp

  script:
    - "git submodule sync --recursive"
    - "git submodule update --init --recursive"
    - "dub build --arch=x86_64 --force"
    - "mv libautowrap-support.so ../../libautowrap.x64.so"

  artifacts:
    paths:
    - libautowrap.x64.so
    expire_in: 1 week

Build Autowrap CSharp Linux x86 Native:
  stage: native
  tags:
    - linux
    - dmd
    - dub 
  only:
    - csharp

  script:
    - "git submodule sync --recursive"
    - "git submodule update --init --recursive"
    - "dub build --arch=x86 --force"
    - "mv libautowrap-support.so ../../libautowrap.x86.so"

  artifacts:
    paths:
    - libautowrap.x86.so
    expire_in: 1 week

Build Autowrap CSharp Windows x64 Native:
  stage: native
  tags:
    - windows
    - dmd
    - dub 
  only:
    - csharp

  script:
    - "git submodule sync --recursive"
    - "git submodule update --init --recursive"
    - "dub build --arch=x86_64 --force"
    - "move autowrap-support.dll ..\\..\\autowrap.x64.dll"

  artifacts:
    paths:
    - autowrap.x64.dll
    expire_in: 1 week

Build Autowrap CSharp Windows x86 Native:
  stage: native
  tags:
    - windows
    - dmd
    - dub 
  only:
    - csharp

  script:
    - "git submodule sync --recursive"
    - "git submodule update --init --recursive"
    - "dub build --arch=x86 --force"
    - "move autowrap-support.dll ..\\..\\autowrap.x86.dll"

  artifacts:
    paths:
    - autowrap.x86.dll
    expire_in: 1 week

Build Autowrap CSharp .NET Library:
  stage: dotnet
  tags:
    - linux
    - dotnet
  only:
    - csharp

  script:
    - "git submodule sync --recursive"
    - "git submodule update --init --recursive"
    - "wget https://gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/libautowrap.x64.so?job=$CI_JOB_NAME"
    - "wget https://gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/libautowrap.x86.so?job=$CI_JOB_NAME"
    - "wget https://gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/autowrap.x64.dll?job=$CI_JOB_NAME"
    - "wget https://gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/autowrap.x86.dll?job=$CI_JOB_NAME"
    - "dotnet build"
    - "dotnet pack"
