language: python
sudo: required
dist: bionic

python:
  - "3.7"

addons:
  apt:
    packages:
      - libclang-6.0-dev

install:
  - pushd /tmp
  - curl -fsS https://dlang.org/install.sh | bash -s ${DC}
  - popd
  - source ~/dlang/${DC}/activate
  - pip install pytest numpy
  # .NET core installation disabled for now due to broken Microsoft repo
  # - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  # - sudo dpkg -i packages-microsoft-prod.deb
  # - sudo apt-get install apt-transport-https
  # - sudo apt-get update
  # - sudo apt-get install dotnet-sdk-2.1

env:
  global:
    - PYTHON_INCLUDE_DIR=~/virtualenv/python3.7/include/python3.7m
    - PYTHON_LIB_DIR=/opt/python/3.7.1/lib
    - PATH=$PYTHON_LIB_DIR:$PATH
    - LD_RUN_PATH=$PYTHON_LIB_DIR:$LD_RUN_PATH
  matrix:
    - DC=dmd-2.085.0
    - DC=dmd-2.085.1
    - DC=dmd-2.086.1
    - DC=dmd-2.087.1
    - DC=dmd-2.088.0

script:
  # Normally this should be ci/test-all.sh but C# is broken due to
  # not being able to install .NET core
  - ci/test-python.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
