language: python
sudo: required
dist: bionic

python:
  - "3.8"

addons:
  apt:
    packages:
      - libclang-6.0-dev

install:
  - pushd /tmp
  - curl -fsS https://dlang.org/install.sh | bash -s ${DC}
  - popd
  - source ~/dlang/${DC}/activate
  - pip install pytest numpy
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1

env:
  global:
    - PYTHON_INCLUDE_DIR=~/virtualenv/python3.8/include/python3.8
    - PYTHON_LIB_DIR=/opt/python/3.8.0/lib
    - PYD_LIBPYTHON_DIR=/opt/python/3.8.0/lib
    - PATH=$PYTHON_LIB_DIR:$PATH
    - LD_RUN_PATH=$PYTHON_LIB_DIR:$PYD_LIBPYTHON_DIR:$LD_RUN_PATH
  matrix:
    - DC=dmd-2.089.0
    - DC=dmd-2.088.1
    - DC=dmd-2.087.1

script:
  #- ci/test-all.sh
  - echo "listing contents of /opt/python/3.8.0/lib"
  - ls /opt/python/3.8.0/lib
  - find /opt/python -name 'libpython*.so'

after_success:
 - bash <(curl -s https://codecov.io/bash)
