language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.082.1
    - d: ldc-1.12.0
  allow_failures:
    - d: dmd-nightly

install:
  - virtualenv autowrapenv
  - source autowrapenv/bin/activate
  - pip install pytest

script:
  - DUB_CONFIGURATION=python27 make
  - dub run pyd:setup && source pyd_set_env_vars.sh
  - DUB_CONFIGURATION=env make
  - dub run -c unittest-travis --build=unittest-cov
  - sh csharp/tests/test.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
