language: python
sudo: required
dist: bionic

python:
  - "3.7"

matrix:
  include:
#    - d: dmd-nightly
    - d: dmd-2.085.0
#    - d: dmd-2.084.1
  # allow_failures:
  #   - d: dmd-nightly

addons:
  apt:
    packages:
      - libclang-3.9-dev
      # - libpython3.7-dev
      # - python3.7


before_install:
  - apt-cache search python3

install:
  - virtualenv autowrapenv
  - source autowrapenv/bin/activate
  - pip install pytest numpy
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1

env:
  global:
    - PYTHON_INCLUDE_DIR=/usr/include/python3.7m
    - PATH=/opt/python/3.7.1/bin:$PATH

script:
  - echo $DC
  - python -VV
  - ls /usr/include/python3.7
  - ls /usr/include/python3.7m
  - ls /opt/python/3.7.1
  - ls /opt/python/3.7.1/include
  - ls ~/virtualenv/python37/include
  # - pynih/ci.sh
  # - DUB_CONFIGURATION=python27 make
  # - dub run pyd:setup && source pyd_set_env_vars.sh
  # - DUB_CONFIGURATION=env make
  # - dub run -c unittest-travis --build=unittest-cov
  # - csharp/tests/test.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
