language: d
sudo: false

matrix:
    include:
        - d: dmd-2.079.1
        - d: ldc-1.8.0
env:
  - DUB_CONFIGURATION=python27

install:
  - virtualenv autowrapenv
  - source autowrapenv/bin/activate
  - pip install pytest

script:
  - make

after_success:
 - bash <(curl -s https://codecov.io/bash)
